export const API_STATUS = {
  IDLE: 'IDLE',
  LOADING: 'LOADING',
  SUCCESS: 'SUCCESS',
  FAILED: 'FAILED',
};

export const LOGIN_PROCESS = {
  IDLE: 'IDLE',
  START: 'START',
  COMPLETE: 'COMPLETE',
};
